### ISSUE TITLE
iOS: detect WiFi enabled/disabled

### ISSUE THREAD

**Issue by eliotg** [eliotg/bounty#1]
Must return true if and only if iPhone/iPod/iPad WiFi is enabled, independent of airplane mode or whether WiFi is connected to a network.  Xamarin/C# would be ideal, but Objective-C, Swift, or C++ is fine too.

Cannot require rooted device or use screen-scraping.  Must be App Store approvable, or at least not known deniable.

I'll close the issue when I can confirm your code passes the above tests.  The easier to verify, the faster it'll get done.  Happy to open source the result if desired, perhaps if nowhere else in an appropriate StackOverflow question.

**Comment by pebble8888** [comment]
https://github.com/alirp88/SMTWiFiStatus
Have you tried it?

**Comment by eliotg** [comment]
Thanks, I'll check it out!

**Comment by eliotg** [comment]
Ok, after an awful lot of research, blood, sweat, and tears, I was able to use that to make what I needed work.  You're the only person who answered my bounty and gave me that link, pebble8888, so I'll happily close this issue and do whatever else is necessary to award you the bounty with my gratitude.
