### ISSUE TITLE
Xamarin Forms on iOS: open KML file with Google Earth

### ISSUE THREAD

**Issue by eliotg** [eliotg/bounty#2]
Given a Xamarin Forms PCL app and Page within it, as well as a KML file stored within application control (e.g. Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)), the code must cause Google Earth to open and render the KML.

It's acceptable to go through intermediate iOS UI such as "what application would you like to open this file with?" as long as the user can reasonably navigate through to Google Earth.  

I know Google Earth can do this, as it works on Android and opening KML files from Mail.  I've tried dozens of variants and examples of UIActivityViewController and UIDocumentInteractionController and haven't been able to get the magical incantation correct.

**Comment by eliotg** [comment]
For reference, he's what the equivalent Android code looks like (and works perfectly):
            Intent intent = new Intent(Intent.ActionView);
            AN.Uri filepath = AN.Uri.FromFile(new Java.IO.File(Path.Combine(GetDataDir(), name)));
            if (name.EndsWith(".kml"))
                intent.SetDataAndType(filepath, "application/vnd.google-earth.kml+xml");
            if (name.EndsWith(".txt"))
                intent.SetDataAndType(filepath, "text/plain");
            Forms.Context.StartActivity(intent);

**Comment by meyer9** [comment]
Hi, I think I could solve this. Where is the code? The repo seems to be empty.

**Comment by meyer9** [comment]
Possible this? https://github.com/xamarin/Xamarin.Forms

**Comment by eliotg** [comment]
Platform.cs has been checked in as the code I've tried. Apologies for how hacked up it is, see previous comment about trying a dozen different things.  

The gist is getting the OpenDataFile() method to work.  The "name" parameter is supposed to be the local filename, but for UI reasons is currently just hacked to the first file in the directory.  The "o" parameter is the Xamarin.Forms.Page hosting the UI which initiates opening of a KML file.

**Comment by arlm** [comment]
Please provide a complete sample with a clean app and your try. Not only a loose class.

**Comment by eliotg** [comment]
We solved this months ago. Thanks and sorry for not being more timely.
